<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>Ticket</h1>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Editar Ticket</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                </div>
            </div>

            <div class="box-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="nome">Nome</label>
                            <input class="form-control" type="text" name="name" maxlength="85" value="Exemplo 1">
                        </div>

                        <div class="form-group">
                            <label for="description">Descrição</label>
                            <textarea name="description" class="form-control" cols="30" rows="10">Exemplo 1 </textarea>
                        </div>

                        <div class="form-group">
                            <label for="priority">Prioridade</label>
                            <select name="priority" class="form-control">
                                        <option value="0">Baixo</option>
                                        <option selected value="1">Médio</option>
                                        <option value="2">Alto</option>
                                    </select>
                        </div>

                        <div class="form-group">
                            <label for="attachment">Arquivos</label>
                            <input type="file" name="attachment" class="form-control" multiple="multiple">
                        </div>
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o"></i> Salvar Ticket</button>
                        </div>
                    </div>
                </form>

                <p><strong>Arquivos</strong></p>
                <ul>
                    <li><a target="_blank" href="#">Arquivo 1</a></li>
                    <li><a target="_blank" href="#">Arquivo 2</a></li>
                    <li><a target="_blank" href="#">Arquivo 3</a></li>
                </ul>
            </div>

            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->